name: update-chromium
on:
  push:
    branches: [ master ]
  # schedule:
  #   - cron:  '* * * * *'

jobs:
  update-to-latest-chromium:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Get Chromium version and update
        run: |
          LASTCHANGE_URL ="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media"
          Mac = "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac%2FLAST_CHANGE?generation=1584339534008794&alt=media"
          Windows = "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win%2FLAST_CHANGE?generation=1584338615619518&alt=media"
          export REVISION=$(curl -s -S $LASTCHANGE_URL)
          echo "latest revision is $REVISION"
          npx json -I -f package.json -e "this.taiko.chromium_revision = $REVISION"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{format('{{{0}{1}{2}}}', 'update-chromium', github.run_id, github.run_number)}}
          commit-message: "update chromium revision"
          title: "update chromium revision"
          body: ""
          

